# Generated by Django 5.2.5 on 2025-09-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("customer", "Customer"),
                    ("freelancer", "Freelancer"),
                ],
                default="freelancer",
                max_length=20,
            ),
        ),
    ]
